export const data = [
    {
      'id': 1,
      'first': 'Jon',
      'last': 'Doe',
      'city': 'San Diego',
      'state': 'CA',
      'age': 124,
    },
    {
      'id': 2,
      'first': 'Bon',
      'last': 'Woe',
      'city': 'San Clemente',
      'state': 'CA',
      'age': 3,
    },
    {
      'id': 3,
      'first': 'Linda',
      'last': 'Watts',
      'city': 'Fort What',
      'state': 'QQ',
      'age': 55,
    },
    {
      'id': 4,
      'first': 'Wendy',
      'last': 'Day',
      'city': 'Happyville',
      'state': 'AB',
      'age': 4022,
    },
    {
      'id': 5,
      'first': 'Tom',
      'last': 'Blicker',
      'city': 'Elberry',
      'state': 'KS',
      'age': 91,
    },
]
